### ISSUE TITLE
根据字段查找点的逻辑

### ISSUE THREAD

**Issue by JasonBian** [FSixteen/janusgraph-utils#2]
在使用非自定义id过程中，根据fkeys和tkeys查找Vertexs时，为什么把label变成type
 starts = starts.has(key.toString().substring(0, key.toString().length() - 1).replaceAll("label", "type"),content.get(key));

**Comment by FSixteen** [comment]
> 在使用非自定义id过程中，根据fkeys和tkeys查找Vertexs时，为什么把label变成type
> starts = starts.has(key.toString().substring(0, key.toString().length() - 1).replaceAll("label", "type"),content.get(key));

查找k:String=v:Object的Vertices时, 可以使用 g.V().has(k, v),
查找label=v1:String or v2:String的Vertices时, 可以使用 g.V().hasLabel(v1, v2),
因为label是内置字段, 所以自定义Props时, 没法再次定义label, 
为了解决这个问题, 在定义Props时, 定义type代替label字段, 所以在业务查询时, 
含有label的字段, 默认替换为type. 只是为了迎合业务需要.
